repos:  
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.3
    hooks:
      # Run the linter.
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format