name: nmem
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - gdspy
  - ipykernel
  - pip:
    - qnnpy
    - git+https://github.com/qnngroup/qnngds.git@OM-1-port-functions
    - phidl
    - pre-commit
    - ruff
    - scipy
    - cycler

