CELLS = {
    "A1": {
        "write_current": 150e-6,
        "read_current": 580e-6,
        "enable_write_current": 351e-6,
        "enable_read_current": 322e-6,
        "slope": -2.384,
        "intercept": 1006.481,
    },
    "A2": {
        "write_current": 0e-6,
        "read_current": 0e-6,
        "enable_write_current": 0e-6,
        "enable_read_current": 0e-6,
        "slope": -0,
        "intercept": 0,
    },
    "A3": {
        "write_current": 0e-6,
        "read_current": 0e-6,
        "enable_write_current": 0e-6,
        "enable_read_current": 0e-6,
        "slope": -0,
        "intercept": 0,
    },
    "A4": {
        "write_current": 0e-6,
        "read_current": 0e-6,
        "enable_write_current": 0e-6,
        "enable_read_current": 0e-6,
        "slope": -0,
        "intercept": 0,
    },
    "B1": {
        "write_current": 0e-6,
        "read_current": 0e-6,
        "enable_write_current": 0e-6,
        "enable_read_current": 0e-6,
        "slope": -0,
        "intercept": 0,
    },
    "B2": {
        "write_current": 30e-6,
        "read_current": 680e-6,
        "enable_write_current": 282.5e-6,
        "enable_read_current": 220e-6,
        "slope": -3.360,
        "intercept": 1453.865,
    },
    "B3": {
        "write_current": 0e-6,
        "read_current": 0e-6,
        "enable_write_current": 0e-6,
        "enable_read_current": 0e-6,
        "slope": -0,
        "intercept": 0,
    },
    "B4": {
        "write_current": 0e-6,
        "read_current": 0e-6,
        "enable_write_current": 0e-6,
        "enable_read_current": 0e-6,
        "slope": -0,
        "intercept": 0,
    },
    "C1": {
        "write_current": 0e-6,
        "read_current": 0e-6,
        "enable_write_current": 0e-6,
        "enable_read_current": 0e-6,
        "slope": -0,
        "intercept": 0,
    },
    "C2": {
        "write_current": 0e-6,
        "read_current": 0e-6,
        "enable_write_current": 0e-6,
        "enable_read_current": 0e-6,
        "slope": -0,
        "intercept": 0,
    },
    "C3": {
        "write_current": 390e-6,
        "read_current": 500e-6,
        "enable_write_current": 246e-6,
        "enable_read_current": 200e-6,
        "slope": -0,
        "intercept": 0,
    },
    "C4": {
        "write_current": 0e-6,
        "read_current": 0e-6,
        "enable_write_current": 0e-6,
        "enable_read_current": 0e-6,
        "slope": -0,
        "intercept": 0,
    },
}
