User:
  name: OM
  
Save File:
  sample name: SPG806
  device type: D6
  device name: A4 # XY Cords A1 in NW corner. D1 in NE corner. 
  cell: C3  # XY Cords A1 in NW corner. D1 in NE corner. 

iv_sweep:
  series_resistance: 1
  series_resistance_g: 1

AWG:
  name: Agilent33250a
  port: 'GPIB0::10::INSTR'
  

Scope: 
  name: LeCroy620Zi
  port: '18.25.30.169'
  channel: [C2]


# Temperature:
#   name: ICE

