# SPICE Simulation Configuration
# This file contains default settings for SPICE circuit simulations

waveforms:
  standard:
    cycle_time: 1.0e-06        # Cycle time in seconds
    pulse_sigma: 3.5e-08       # Pulse sigma in seconds  
    hold_width_write: 1.2e-07  # Write pulse hold width in seconds
    hold_width_read: 3.0e-07   # Read pulse hold width in seconds
    hold_width_clear: 5.0e-09  # Clear pulse hold width in seconds
    write_amplitude: 8.0e-05   # Write current amplitude in Amperes
    read_amplitude: 7.25e-04   # Read current amplitude in Amperes
    enab_write_amplitude: 4.65e-04  # Enable write current amplitude in Amperes
    enab_read_amplitude: 3.0e-04    # Enable read current amplitude in Amperes  
    clear_amplitude: 7.0e-04   # Clear current amplitude in Amperes
    dt: 1.0e-10               # Time step in seconds
    seed: 42                  # Random seed for reproducible results

simulation:
  ltspice_path: "/mnt/c/Users/omedeiro/AppData/Local/Programs/ADI/LTspice/LTspice.exe"
  template_netlist: "default_circuit_template.cir"
  output_format: "csv"
  logging_level: "INFO"

paths:
  data_dir: null            # Will use default if null
  results_dir: null         # Will use default if null
  circuit_files_dir: null   # Will use default if null
  templates_dir: null       # Will use default if null

plotting:
  figure_size: [12, 6]
  dpi: 300
  font_size: 12
  line_width: 1.5
  grid: true
  style: "default"
