# Fast waveform parameters for quick simulation  
waveforms:
  standard:
    cycle_time: 5.0e-07     # 500 ns cycles (2x faster than default, was 2e-07)
    pulse_sigma: 2.5e-08    # 25 ns sigma (1.4x faster than default, was 1.5e-08)
    hold_width_write: 6.0e-08   # 60 ns write hold (2x faster than default, was 2e-08)
    hold_width_read: 1.5e-07    # 150 ns read hold (2x faster than default, was 5e-08)
    hold_width_clear: 5.0e-09
    write_amplitude: 8.0e-05
    read_amplitude: 7.25e-04
    enab_write_amplitude: 4.6e-04   # 460 µA
    enab_read_amplitude: 3.0e-04
    clear_amplitude: 7.0e-04
    dt: 1.0e-10
    seed: 42                # Random seed for reproducible results

simulation:
  ltspice_path: "/mnt/c/Users/omedeiro/AppData/Local/Programs/ADI/LTspice/LTspice.exe"
  template_netlist: "default_circuit_template.cir"
  output_format: "csv"
  logging_level: "INFO"
  # Simulation timing parameters
  start_time: 0
  stop_time: 25e-6      # 25 microseconds (half of default 50u)
  start_save: 0         # When to start saving data
  time_step: 1e-9       # 1 nanosecond

paths:
  data_dir: null
  results_dir: null
  circuit_files_dir: null
  templates_dir: null

plotting:
  figsize: [6, 4]  # Smaller figure size
  dpi: 120         # Lower DPI for smaller interactive windows
  font_size: 7
  line_width: 1.5
  grid: true
  style: "technical"